---
title: "Homework assignment - Docker"
author: "Samantha Pang"
output: 
  html_document:
    df_print: paged
---
## Task 1:
Create a 5 by 10 matrix of random integers
```{r}
set.seed(4505)
randomInts <- sample.int(100, 50, replace = TRUE) # Generate 50 random integers
matrixInts <- matrix(randomInts, nrow = 5, ncol = 10) # 5 x 10 matrix 
matrixInts
```

## Task 2:
Define column names as cond1, cond2, cond3, cond4, cond5, ctrl1, ctrl2, ctrl3, ctrl4, ctrl5
```{r}
colnames(matrixInts) <- c("cond1", "cond2", "cond3", "cond4", "cond5",
                          "ctrl1", "ctrl2", "ctrl3", "ctrl4", "ctrl5")
matrixInts
```

## Task 3:
Define row names as gene1, gene2, gene3 ...
```{r}
rownames(matrixInts) <- c("gene1", "gene2", "gene3", "gene4", "gene5")
matrixInts
```

## Task 4:
Compute the fold change for each gene where each condition corresponds to each control for a gene.

The log2 fold-change is log2(FC) = log2(mean(Group1)/mean(Group2))

```{r}
cond <- matrixInts[, 1:5]
ctrl <- matrixInts[, 6:10]
log2FoldChange <- log2(cond/ctrl)
log2FoldChange
```


